[theme]
base = "light"
primaryColor = "#0054D1"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#ECF2FA"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true

[runner]
fastReruns = true
